# Generated by Django 2.2.3 on 2019-12-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191218_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_item_decription',
            field=models.CharField(max_length=200),
        ),
    ]
